services:
  - type: web
    name: tg-book-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SHEET_CSV_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
