services:
  - type: worker
    name: tg-book-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SHEET_CSV_URL
        sync: false
